# Generated by Django 4.2.7 on 2024-01-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_categories_options_alter_categories_name_and_more'),
        ('goods', '0003_alter_products_options'),
    ]

    operations = [
    ]
